### ISSUE TITLE
Dockerise all the components used in article manager

### ISSUE THREAD

**Issue by ravik-karn** [ILearntToday/article-manager#8]
#Tasks
- [ ] Setup travis for the repo
- [ ] Setup docker registery for the repo
- [ ] Create travis yml
- [ ] Create dockerfile

#AC
- [ ] PR check should happen for each PR
- [ ] After merge to master automatically a docker image should be published
- [ ] Pull the docker image and run
